### ISSUE TITLE
SELinux issues

### ISSUE THREAD

**Issue by hackrid** [Viknet/cnping-android#1]
With the latest alpha build I still get an error message which says:

Cannot get sockets with su. 

My phone (Android 6) is rooted, SELinux set to permit.

**Comment by Viknet** [comment]
Can you run `adb logcat | grep cnping`?

**Comment by hackrid** [comment]
I don't have a computer available

**Comment by hackrid** [comment]
Logcat on the device does not show anything

**Comment by Viknet** [comment]
SuperSU installed? Did it show "Superuser request" or something?

**Comment by Viknet** [comment]
logcat on device will show something only if run from root.

**Comment by hackrid** [comment]
I don't have access to a computer. 

Here is a logcat dump:

FulmicsROM:/ $ su 0 logcat | grep cnping
06-10 22:10:01.462 29652 29652 I Timeline: Timeline: Activity_launch_request id:com.viknet.cnping time:93771886
06-10 22:10:01.464  3531  4990 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.viknet.cnping/.MainActivity} from uid 10050 on display 0
06-10 22:10:01.489  3531  4990 V SplitWindowManager: findTaskLocked set ActivitySplitInfo [screenZone=0/ flag=0x1000/ state=NATIVE/ forceFullScreen=false] to ActivityRecord{10575f6 u0 com.viknet.cnping/.MainActivity t11824}
06-10 22:10:01.489  3531  4990 V SplitWindowManager: bringStackToFront : ActivityRecord{10575f6 u0 com.viknet.cnping/.MainActivity t11824}
06-10 22:10:01.493  3531  4990 D ActivityManager: setTaskToReturnTo : TaskRecord{9ae0291 #11824 A=com.viknet.cnping U=0 sz=1} / mTaskToReturnTo = 1
06-10 22:10:01.526  3531  5026 I ActivityManager: Start proc 18454:com.viknet.cnping/u0a193 for activity com.viknet.cnping/.MainActivity
06-10 22:10:01.570 11867 11878 D AppInfoDao: topacitivyt exist app = com.viknet.cnping
06-10 22:10:01.577 11867 11878 D AppInfoDao: topacitivyt update app = com.viknet.cnping time = 2017-06-10 22:10 date = 20170610
06-10 22:10:01.609  3531  3731 I SystemUI[Framework]: PhoneWindowManager.updateSystemUiVisibilityLw() :visibility=0x0, pkg=com.viknet.cnping
06-10 22:10:01.611  3531  3731 D StatusBarManagerServiceEx: manageNaviBtnDisableList userId=0 what=0x0 pkg=Window{737a904 u0 Starting com.viknet.cnping}
06-10 22:10:01.611  3531  3731 I SystemUI[Framework]: ==>disabledNaviBtn() what=0x0, token=android.os.Binder@8452273,  pkg=Window{737a904 u0 Starting com.viknet.cnping}
06-10 22:10:01.689 18454 18474 I cnping:pinger: SELinux is not enforced.
06-10 22:10:01.763 18488 18488 E cnping:helper: Set timeout failed
06-10 22:10:01.778  3531  5019 D InputDispatcher: Focus entered window: Window{9fd7ea5 u0 com.viknet.cnping/com.viknet.cnping.MainActivity}
06-10 22:10:01.973 18454 18474 I cnping:pinger: Helper exit: 65280
06-10 22:10:01.973 18454 18474 E cnping:pinger: Helper failed.
06-10 22:10:02.126  3531  3789 I ActivityManager: Displayed com.viknet.cnping/.MainActivity: +620ms06-10 22:10:02.128  3531  3789 D InputDispatcher: Window went away: Window{737a904 u0 Starting com.viknet.cnping}
06-10 22:10:02.296 18454 18454 V ViewRootImpl: Contents drawing finished : com.viknet.cnping/com.viknet.cnping.MainActivity
06-10 22:10:02.324  3531  5017 D InputDispatcher: Focus left window: Window{9fd7ea5 u0 com.viknet.cnping/com.viknet.cnping.MainActivity}
06-10 22:10:02.324  3531  5017 D InputDispatcher: Focus entered window: Window{4855e07 u0 com.viknet.cnping/com.viknet.cnping.MainActivity}
06-10 22:10:02.331  3531  3731 I SystemUI[Framework]: PhoneWindowManager.updateSystemUiVisibilityLw() :visibility=0x8000, pkg=com.viknet.cnping
06-10 22:10:02.347  3531  3731 D StatusBarManagerServiceEx: manageNaviBtnDisableList userId=0 what=0x0 pkg=Window{4855e07 u0 com.viknet.cnping/com.viknet.cnping.MainActivity}
06-10 22:10:02.347  3531  3731 I SystemUI[Framework]: ==>disabledNaviBtn() what=0x0, token=android.os.Binder@8452273,  pkg=Window{4855e07 u0 com.viknet.cnping/com.viknet.cnping.MainActivity}
06-10 22:10:02.901 18454 18454 V ViewRootImpl: Contents drawing finished : com.viknet.cnping/com.viknet.cnping.MainActivity
06-10 22:10:03.978  3531  3731 I SystemUI[Framework]: PhoneWindowManager.updateSystemUiVisibilityLw() :visibility=0x8600, pkg=com.viknet.cnping
06-10 22:10:03.979  3531  5060 D InputDispatcher: Focus left window: Window{4855e07 u0 com.viknet.cnping/com.viknet.cnping.MainActivity}
06-10 22:10:03.979  3531  3731 D StatusBarManagerServiceEx: manageNaviBtnDisableList userId=0 what=0x0 pkg=Window{9fd7ea5 u0 com.viknet.cnping/com.viknet.cnping.MainActivity}
06-10 22:10:03.979  3531  3731 I SystemUI[Framework]: ==>disabledNaviBtn() what=0x0, token=android.os.Binder@8452273,  pkg=Window{9fd7ea5 u0 com.viknet.cnping/com.viknet.cnping.MainActivity}
06-10 22:10:05.147  3531  4452 D ActivityManager: setTaskToReturnTo : TaskRecord{9ae0291 #11824 A=com.viknet.cnping U=0 sz=1} / mTaskToReturnTo = 1
FulmicsROM:/ $

**Comment by Viknet** [comment]
@hackrid Thank you for help.
I think it isn't SELinux issue.
`setsockopt SO_RCVTIMEO` somehow failed on Android 6, but working on 4 and 5.
I will switch to O_NONBLOCK and make new build today.

**Comment by Viknet** [comment]
Try new release: https://github.com/Viknet/cnping-android/releases/tag/0.0.1c

For more clear messages you can add colon to grep: `su 0 logcat | grep "cnping:"`

**Comment by hackrid** [comment]
Thanks! With this change it works now!

**Comment by Viknet** [comment]
Can you test it with enabled SELinux?
`su 0 setenforce 1`

**Comment by hackrid** [comment]
Hey, 
I tried it. Doesn't work. Here's the log. 
But I think my phone is not meant to have selinux in enforced mode. All the system apps ceep on crashing, so you might consider someone else to test under enforced selinux settings 

FulmicsROM:/ $ su 0 setenforce 1
FulmicsROM:/ $ su 0 logcat| grep 'cnping:'
06-11 15:19:29.709 12038 12069 I cnping:pinger: SELinux enforced. Patching policies.
06-11 15:19:29.830 12038 12069 I cnping:pinger: OUTPUT: supolicy v2.82 (ndk:armeabi-v7a) - Copyright (C) 2014-2017 - Chainfire & CCMT
06-11 15:19:29.830 12038 12069 I cnping:pinger: OUTPUT:
06-11 15:19:29.831 12038 12069 I cnping:pinger: OUTPUT: Patching policy ...
06-11 15:19:29.842 12038 12069 I cnping:pinger: OUTPUT: - Failure! 2
06-11 15:19:30.386 12038 12069 I cnping:pinger: Helper exit: 0
06-11 15:19:30.386 12038 12069 E cnping:pinger: bad cmsg header / message length
06-11 15:19:30.386 12038 12069 E cnping:pinger: Ping socket retreival failed

**Comment by Viknet** [comment]
So, your phone was initially in permissive mode?

**Comment by hackrid** [comment]
Yes, exactly

**Comment by Viknet** [comment]
Ok, I guess this issue is done then.
