### ISSUE TITLE
CNFGClearFrame uses uninitialized variables

### ISSUE THREAD

**Issue by trogper** [Viknet/cnping-android#2]
in functionCNFGClearFrame, x and y are used to initialize m, but they are not initialized.
change line `short x, y;` to `short x = bufferx, y = buffery;`

**Comment by Viknet** [comment]
And how it was working before?..
Fixed in 0.0.3

Btw i don't have android anymore. If you like this app feel free to fork and make it usable

**Comment by trogper** [comment]
I'd like to know that too.
btw I have converted the project to gradle and cmake in android studio 3.3 and am running it on android 8.1

**Comment by Viknet** [comment]
That's cool!
I could't figure out how to integrate NDK lib in graddle project.

Will you publish results?

**Comment by trogper** [comment]
I have forked it and commited my changes. It does work on Galaxy J5 2015 with lineage 8.1 and does not on Nexus 6 with AOSP 8.1.
It fails on "bad cmsg header / message length", didn't have the time yet to debug it propely. I suppose the higher screen resolution might be the cause. (2560x1440 vs 1280x720)

**Comment by Viknet** [comment]
I think it is something around SELinux.
Passing socket permissions to another process is not supported by NDK and requires rooting phone and patching SELinux policies. But all devices have different configurations.
I made this app work on 3 devices and several emulators but it is not a universal solution.

**Comment by trogper** [comment]
You are right, disabling selinux allows it to work on nexus 6 too.
What about chcon?
